### ISSUE TITLE
Missing Arguments at 'help'

### ISSUE THREAD

**Issue by Yuan-San** [Dok4440/ProjectAx#5]
![beta-testing — Mozilla Firefox 7_2_2021 8_38_31 AM (2)_LI](https://user-images.githubusercontent.com/67492199/124208115-1947e080-db11-11eb-88d1-070ee76c1d28.jpg)

I got an error warning when typing 'ax help'. it shows an argument(s) is missing. when it wasn't. I'm thinking this bug was coming because 'help' needs certain param to show a specific command help.

**Comment by Dok4440** [comment]
Fixed this is [v1.3.10-a](https://github.com/Dok4440/ProjectAx/commit/4be012314e32024ffa598644b21fa989333067e3). Thanks for reporting the bug.
