### ISSUE TITLE
'pvp' Weapon Confirmation Message Stuck

### ISSUE THREAD

**Issue by Yuan-San** [Dok4440/ProjectAx#6]
![general — Mozilla Firefox 7_3_2021 2_54_43 PM (2)](https://user-images.githubusercontent.com/67492199/124347422-f00d7a00-dc0e-11eb-8ef3-9af784360fd7.png)

[Message Link](https://discord.com/channels/803957895603027978/839537047470473227/860789258889068545)
Nearby Version:  v1.3.9-a - Moderation push

'pvp' command are stuck when its confirming player to choose their weapon.

**Comment by Dok4440** [comment]
As the pvp training modules aren't done yet and the commands aren't completed, there's a lot of bugs to be found in them. A proper release of Project Ax's combat system will come soon.
